<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_license_manager.proto

namespace GPBMetadata\Proto;

class GoLicenseManager
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
b
proto/go_license_manager.protolicenseManagerGrpc2
licenseManagerBZlicense_manager/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

