<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_local_license.proto

namespace GPBMetadata\Proto;

class GoLocalLicense
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Z
proto/go_local_license.protolocalLicenseGrpc2
localLicenseBZlocal_license/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

