// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: proto/go_license_manager.proto

package license_manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_go_license_manager_proto protoreflect.FileDescriptor

var file_proto_go_license_manager_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x5f, 0x6c, 0x69, 0x63, 0x65, 0x6e,
	0x73, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x47, 0x72, 0x70, 0x63, 0x32, 0x10, 0x0a, 0x0e, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x42, 0x12, 0x5a, 0x10, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73,
	0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var file_proto_go_license_manager_proto_goTypes = []interface{}{}
var file_proto_go_license_manager_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_go_license_manager_proto_init() }
func file_proto_go_license_manager_proto_init() {
	if File_proto_go_license_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_go_license_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_go_license_manager_proto_goTypes,
		DependencyIndexes: file_proto_go_license_manager_proto_depIdxs,
	}.Build()
	File_proto_go_license_manager_proto = out.File
	file_proto_go_license_manager_proto_rawDesc = nil
	file_proto_go_license_manager_proto_goTypes = nil
	file_proto_go_license_manager_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LicenseManagerClient is the client API for LicenseManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LicenseManagerClient interface {
}

type licenseManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewLicenseManagerClient(cc grpc.ClientConnInterface) LicenseManagerClient {
	return &licenseManagerClient{cc}
}

// LicenseManagerServer is the server API for LicenseManager service.
type LicenseManagerServer interface {
}

// UnimplementedLicenseManagerServer can be embedded to have forward compatible implementations.
type UnimplementedLicenseManagerServer struct {
}

func RegisterLicenseManagerServer(s *grpc.Server, srv LicenseManagerServer) {
	s.RegisterService(&_LicenseManager_serviceDesc, srv)
}

var _LicenseManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "licenseManagerGrpc.licenseManager",
	HandlerType: (*LicenseManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/go_license_manager.proto",
}
